# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2024.1.1-209-g114889c
_src_path: gh:blakeNaccarato/copier-python
actions_runner: ubuntu-22.04
active: false
github_repo_name: context_models
project_description: Context models
project_email: blake.naccarato@gmail.com
project_name: context_models
project_owner_github_username: softboiler
project_owner_name: Blake Naccarato, Kwang Jin Kim
project_version: 0.0.1
python_version: '3.11'
year_of_project_creation: 2022
